---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: uat-$ServiceName
    version: primary
  name: uat-$ServiceName
  namespace: $Namespace
spec:
  selector:
    matchLabels:
      type: uat-$ServiceName
  template:
    metadata:
      labels:
        type: uat-$ServiceName
        version: primary
    spec:
      serviceAccountName: uat-$ServiceName-sa
      containers:
        - name: uat-$ServiceName
          env:
            - name: NODE_ENV
              value: uat
            - name: APP_NAME
              value: $ServiceName
            - name: LOG_LEVEL
              value: debug
          image: <ECR_REPO_NAME>
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: <Health_check_path> # The path to your health check endpoint
              port: 3000 # The port on which your NestJS application runs
            initialDelaySeconds: 180 # Delay before the first probe is initiated
            periodSeconds: 20
          resources:
            limits:
              cpu: 1
              memory: 1800Mi
            requests:
              cpu: 1
              memory: 1000Mi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: uat-$ServiceName
  namespace: $Namespace
spec:
  ports:
    - name: uat-$ServiceName
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    type: uat-$ServiceName
  type: ClusterIP
