image:
  name: 287726214764.dkr.ecr.ap-south-1.amazonaws.com/base/node:node-21-alpine-root
  aws:
    oidc-role: <OIDC_ROLE>

definitions:
  services:
    docker:
      memory: 1024

  steps:
    - step: &Snyk_Check
        name: snyk-vulnerability-check
        oidc: true
        size: 2x
        script:
          - npm cache clean --force
          - npm install --force ./server
          - pipe: snyk/snyk-scan:0.5.2
            variables:
              SNYK_TOKEN: ${SNYK_Token}
              LANGUAGE: "npm"
              DONT_BREAK_BUILD: "true"
              DEBUG: "true"
              MONITOR: "false"
              CODE_INSIGHTS_RESULTS: "true"
        services:
          - docker
    - step: &Sonar_Quality_Check
        name: Scanning sonar cloud
        oidc: true
        size: 2x
        script:
          - export SONAR_TOKEN=${SONAR_TOKEN}
          - export SONAR_URL=https://sonarcloud.io/
          - export SONAR_ORG=niyo-solutions-inc
          - export SONAR_PROJECT_KEY=niyo-solutions-inc_$ServiceName
          - export NODE_ENV=uat
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: "-Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.projectName=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_URL -Dsonar.sources=. -Dsonar.exclusions=**/*.spec.ts,**/*.mock.ts,src/config/**,Dockerfile,!src/config/configuration.ts"
        services:
          - docker
    - step: &Secret_Scan
        name: Scanning secrets
        oidc: true
        size: 2x
        caches:
          - node
        script:
          - pipe: atlassian/git-secrets-scan:0.6.1
            variables:
              FILES: "."
              ANNOTATION_SUMMARY: "Credentials found in code."
        services:
          - docker
    - step: &ECR_Image_check
        name: "ECR"
        oidc: true
        size: 2x
        services:
          - docker
        script:
          - export AWS_AWS_ECR_REPOSITORYSITORY_UAT="287726214764.dkr.ecr.ap-south-1.amazonaws.com/niyox2/x2-core-algo-risk-analysis-backend"
          - export IMAGE_NAME_COMMIT=$AWS_AWS_ECR_REPOSITORYSITORY_UAT
          - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.16.0
          - trivy image $IMAGE_NAME_COMMIT:$BITBUCKET_BRANCH-$BITBUCKET_COMMIT | tee results.txt
          - cat results.txt
          - >
            if grep -q "Total: 0 (LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)" results.txt; then
              echo "No vulnerabilities found. Proceeding with deployment."
            else
              echo "Vulnerabilities found. Pipeline will fail."
            fi

    - step: &Build_Image
        name: "DOCKER_IMAGE_BUILD"
        oidc: true
        size: 2x
        services:
          - docker
        script:
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - export AWS_ROLE_ARN=UAT_OIDC
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - export AWS_ECR=AWS_ECR_REPOSITORY
          - export IMAGE_NAME_COMMIT=$AWS_ECR
          - npm install -g @nestjs/cli
          - cd server
          - pwd
          - npm install
          - npm run build
          - cd ..
          - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 287726214764.dkr.ecr.ap-south-1.amazonaws.com
          - docker build -f Dockerfile -t $IMAGE_NAME_COMMIT:$BITBUCKET_BRANCH-$BITBUCKET_COMMIT .
          - docker push $IMAGE_NAME_COMMIT:$BITBUCKET_BRANCH-$BITBUCKET_COMMIT

    - step: &DEPLOY_DEV
        name: "EKS_Deploy"
        image: atlassian/pipelines-awscli
        size: 2x
        oidc: true
        script:
          - apk add wget
          - wget -O kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.18.9/2020-11-02/bin/linux/amd64/kubectl
          - mkdir ~/.kube
          - cp .kube/config/dev-config.yml ~/.kube/config
          - chmod +x ./kubectl
          - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - export AWS_ROLE_ARN=UAT_OIDC
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - sed -i 's/\$IMGTAG'"/$BITBUCKET_BRANCH-$BITBUCKET_COMMIT/g" .kube/deployment/dev-deployment.yml
          - kubectl apply -f .kube/deployment/uat-deployment.yml

    - step: &DEPLOY_UAT
        name: "EKS_Deploy"
        image: atlassian/pipelines-awscli
        size: 2x
        oidc: true
        script:
          - apk add wget
          - wget -O kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.18.9/2020-11-02/bin/linux/amd64/kubectl
          - mkdir ~/.kube
          - cp .kube/config/uat-config.yml ~/.kube/config
          - chmod +x ./kubectl
          - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - export AWS_ROLE_ARN=UAT_OIDC
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - sed -i 's/\$IMGTAG'"/$BITBUCKET_BRANCH-$BITBUCKET_COMMIT/g" .kube/deployment/uat-deployment.yml
          - kubectl apply -f .kube/deployment/uat-deployment.yml
        services:
          - docker

    - step: &DEPLOY_BETA
        name: "EKS_Deploy_BETA"
        image: atlassian/pipelines-awscli
        size: 2x
        oidc: true
        script:
          - apk add wget
          - wget -O kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.18.9/2020-11-02/bin/linux/amd64/kubectl
          - mkdir ~/.kube
          - cp .kube/config/beta-config.yml ~/.kube/config
          - chmod +x ./kubectl
          - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - export AWS_ROLE_ARN=PROD_OIDC
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - sed -i 's/\$IMGTAG'"/$BITBUCKET_BRANCH-$BITBUCKET_COMMIT/g" .kube/deployment/beta-deployment.yml
          - kubectl apply -f .kube/deployment/beta-deployment.yml
        services:
          - docker

    - step: &DEPLOY_PROD
        name: "EKS_Deploy_PROD"
        image: atlassian/pipelines-awscli
        size: 2x
        oidc: true
        trigger: manual
        script:
          - apk add wget
          - wget -O kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.18.9/2020-11-02/bin/linux/amd64/kubectl
          - mkdir ~/.kube
          - cp .kube/config/prod-config.yml ~/.kube/config
          - chmod +x ./kubectl
          - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - export AWS_ROLE_ARN=PROD_OIDC
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - sed -i 's/\$IMGTAG'"/$BITBUCKET_BRANCH-$BITBUCKET_COMMIT/g" .kube/deployment/prod-deployment.yml
          - kubectl apply -f .kube/deployment/prod-deployment.yml
        services:
          - docker

pipelines:
  custom:
    code-review:
      - parallel:
          - step: *Sonar_Quality_Check
          - step: *Snyk_Check
          - step: *Secret_Scan
  branches:
    uat-deployment:
      - parallel:
          - step: *Sonar_Quality_Check
          - step: *Secret_Scan
          - step: *ECR_Image_check
          - step: *Snyk_Check
      - step: *Build_Image
      - step: *DEPLOY_DEV
    uat-integration:
      - parallel:
          - step: *Sonar_Quality_Check
          - step: *Secret_Scan
          - step: *Snyk_Check
          - step: *ECR_Image_check
      - step: *Build_Image
      - step: *DEPLOY_UAT
    beta-integration:
      - parallel:
          - step: *Sonar_Quality_Check
          - step: *Snyk_Check
          - step: *Secret_Scan
          - step: *ECR_Image_check
      - step: *Build_Image
      - step: *DEPLOY_BETA
    master:
      - parallel:
          - step: *Sonar_Quality_Check
          - step: *Snyk_Check
          - step: *Secret_Scan
          - step: *ECR_Image_check
      - step: *Build_Image
      - step: *DEPLOY_PROD
